import type { Book, BookFormat, BookLanguage } from '../models/book.js';

interface SeedBook {
  readonly title: string;
  readonly author: string;
  readonly publisher: string;
  readonly genre: string;
  readonly language: BookLanguage;
  readonly publishedYear: number;
  readonly pageCount: number;
  readonly format: BookFormat;
  readonly priceCents: number;
  readonly oldPriceCents?: number;
  readonly stock: number;
  readonly rating: number;
  readonly reviewCount: number;
  readonly description: string;
}

const HARDCOVER: BookFormat = 'hardcover';
const PAPERBACK: BookFormat = 'paperback';
const AUDIO: BookFormat = 'audiobook';

const SEED: readonly SeedBook[] = [
  {
    title: 'Solaris',
    author: 'Stanisław Lem',
    publisher: 'Wydawnictwo Literackie',
    genre: 'sci-fi',
    language: 'pl',
    publishedYear: 1961,
    pageCount: 224,
    format: HARDCOVER,
    priceCents: 4900,
    oldPriceCents: 5900,
    stock: 18,
    rating: 4.7,
    reviewCount: 412,
    description: 'Klasyk SF o stacji badawczej na planecie pokrytej oceanem.',
  },
  {
    title: 'Cyberiada',
    author: 'Stanisław Lem',
    publisher: 'Wydawnictwo Literackie',
    genre: 'sci-fi',
    language: 'pl',
    publishedYear: 1965,
    pageCount: 280,
    format: PAPERBACK,
    priceCents: 3900,
    stock: 22,
    rating: 4.6,
    reviewCount: 198,
    description: 'Wynalazcze przygody Trurla i Klapaucjusza.',
  },
  {
    title: 'Pan Tadeusz',
    author: 'Adam Mickiewicz',
    publisher: 'Greg',
    genre: 'poetry',
    language: 'pl',
    publishedYear: 1834,
    pageCount: 380,
    format: PAPERBACK,
    priceCents: 2500,
    stock: 50,
    rating: 4.5,
    reviewCount: 678,
    description: 'Epopeja narodowa.',
  },
  {
    title: 'Lalka',
    author: 'Bolesław Prus',
    publisher: 'PIW',
    genre: 'fiction',
    language: 'pl',
    publishedYear: 1890,
    pageCount: 720,
    format: HARDCOVER,
    priceCents: 5900,
    stock: 14,
    rating: 4.6,
    reviewCount: 234,
    description: 'Społeczna panorama Warszawy końca XIX wieku.',
  },
  {
    title: 'Wiedźmin: Ostatnie życzenie',
    author: 'Andrzej Sapkowski',
    publisher: 'SuperNowa',
    genre: 'fantasy',
    language: 'pl',
    publishedYear: 1993,
    pageCount: 336,
    format: PAPERBACK,
    priceCents: 3500,
    stock: 38,
    rating: 4.8,
    reviewCount: 956,
    description: 'Pierwszy zbiór opowiadań o Geralcie z Rivii.',
  },
  {
    title: 'Wiedźmin: Krew elfów',
    author: 'Andrzej Sapkowski',
    publisher: 'SuperNowa',
    genre: 'fantasy',
    language: 'pl',
    publishedYear: 1994,
    pageCount: 318,
    format: PAPERBACK,
    priceCents: 3500,
    stock: 28,
    rating: 4.7,
    reviewCount: 612,
    description: 'Pełnowymiarowa powieść sagi o Wiedźminie.',
  },
  {
    title: 'Ferdydurke',
    author: 'Witold Gombrowicz',
    publisher: 'PIW',
    genre: 'fiction',
    language: 'pl',
    publishedYear: 1937,
    pageCount: 312,
    format: PAPERBACK,
    priceCents: 3200,
    stock: 12,
    rating: 4.4,
    reviewCount: 143,
    description: 'Groteskowy debiut prozatorski.',
  },
  {
    title: 'Sapkowski. Saga o Wiedźminie (audio)',
    author: 'Andrzej Sapkowski',
    publisher: 'Audioteka',
    genre: 'fantasy',
    language: 'pl',
    publishedYear: 2019,
    pageCount: 0,
    format: AUDIO,
    priceCents: 7900,
    stock: 99,
    rating: 4.6,
    reviewCount: 312,
    description: 'Pełna audiobookowa saga o Geralcie.',
  },

  {
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    publisher: 'HarperCollins',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1954,
    pageCount: 1216,
    format: HARDCOVER,
    priceCents: 14900,
    oldPriceCents: 16900,
    stock: 15,
    rating: 4.9,
    reviewCount: 2456,
    description: 'Epic quest to destroy the One Ring.',
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    publisher: 'HarperCollins',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1937,
    pageCount: 310,
    format: PAPERBACK,
    priceCents: 4500,
    stock: 24,
    rating: 4.8,
    reviewCount: 1834,
    description: "Bilbo's unexpected journey.",
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    publisher: 'Ace',
    genre: 'sci-fi',
    language: 'en',
    publishedYear: 1965,
    pageCount: 412,
    format: PAPERBACK,
    priceCents: 5200,
    stock: 31,
    rating: 4.7,
    reviewCount: 1023,
    description: 'Spice and power on desert planet Arrakis.',
  },
  {
    title: 'Foundation',
    author: 'Isaac Asimov',
    publisher: 'Bantam',
    genre: 'sci-fi',
    language: 'en',
    publishedYear: 1951,
    pageCount: 244,
    format: PAPERBACK,
    priceCents: 4200,
    stock: 19,
    rating: 4.6,
    reviewCount: 567,
    description: "Psychohistory predicts the empire's fall.",
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: 'J.K. Rowling',
    publisher: 'Bloomsbury',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1997,
    pageCount: 332,
    format: HARDCOVER,
    priceCents: 6900,
    stock: 45,
    rating: 4.9,
    reviewCount: 3211,
    description: 'A boy discovers he is a wizard.',
  },
  {
    title: '1984',
    author: 'George Orwell',
    publisher: 'Penguin',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1949,
    pageCount: 328,
    format: PAPERBACK,
    priceCents: 3900,
    stock: 51,
    rating: 4.7,
    reviewCount: 2189,
    description: 'Dystopian critique of totalitarianism.',
  },
  {
    title: 'Animal Farm',
    author: 'George Orwell',
    publisher: 'Penguin',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1945,
    pageCount: 112,
    format: PAPERBACK,
    priceCents: 2900,
    stock: 64,
    rating: 4.6,
    reviewCount: 1567,
    description: 'Allegorical farm where pigs take over.',
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    publisher: 'Harper',
    genre: 'non-fiction',
    language: 'en',
    publishedYear: 2011,
    pageCount: 464,
    format: HARDCOVER,
    priceCents: 6500,
    stock: 33,
    rating: 4.7,
    reviewCount: 1923,
    description: 'A panoramic history of our species.',
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    publisher: 'Farrar, Straus and Giroux',
    genre: 'non-fiction',
    language: 'en',
    publishedYear: 2011,
    pageCount: 499,
    format: PAPERBACK,
    priceCents: 5700,
    stock: 27,
    rating: 4.6,
    reviewCount: 1456,
    description: 'Two systems of human thought.',
  },
  {
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    publisher: 'Bantam',
    genre: 'science',
    language: 'en',
    publishedYear: 1988,
    pageCount: 256,
    format: PAPERBACK,
    priceCents: 4900,
    stock: 22,
    rating: 4.6,
    reviewCount: 987,
    description: 'Cosmology for everyone.',
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publisher: 'Penguin',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1813,
    pageCount: 432,
    format: PAPERBACK,
    priceCents: 3500,
    stock: 41,
    rating: 4.7,
    reviewCount: 1834,
    description: 'Bennet sisters navigate love and class.',
  },
  {
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    publisher: 'Knopf',
    genre: 'mystery',
    language: 'en',
    publishedYear: 2005,
    pageCount: 590,
    format: PAPERBACK,
    priceCents: 4800,
    stock: 18,
    rating: 4.6,
    reviewCount: 1234,
    description: 'Journalist and hacker probe a vanished heiress.',
  },
  {
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    publisher: 'Crown',
    genre: 'mystery',
    language: 'en',
    publishedYear: 2012,
    pageCount: 422,
    format: PAPERBACK,
    priceCents: 4500,
    stock: 24,
    rating: 4.5,
    reviewCount: 1089,
    description: 'Marriage gone darkly wrong.',
  },
  {
    title: 'Becoming',
    author: 'Michelle Obama',
    publisher: 'Crown',
    genre: 'biography',
    language: 'en',
    publishedYear: 2018,
    pageCount: 448,
    format: HARDCOVER,
    priceCents: 8900,
    stock: 19,
    rating: 4.8,
    reviewCount: 1567,
    description: 'Memoir of the former First Lady.',
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    publisher: 'Random House',
    genre: 'biography',
    language: 'en',
    publishedYear: 2018,
    pageCount: 334,
    format: HARDCOVER,
    priceCents: 7900,
    stock: 14,
    rating: 4.7,
    reviewCount: 1267,
    description: 'Memoir of self-education against the odds.',
  },

  {
    title: 'Le Petit Prince',
    author: 'Antoine de Saint-Exupéry',
    publisher: 'Gallimard',
    genre: 'fiction',
    language: 'fr',
    publishedYear: 1943,
    pageCount: 96,
    format: HARDCOVER,
    priceCents: 4500,
    stock: 27,
    rating: 4.9,
    reviewCount: 1089,
    description: 'A pilot meets a young prince in the desert.',
  },
  {
    title: "L'Étranger",
    author: 'Albert Camus',
    publisher: 'Gallimard',
    genre: 'fiction',
    language: 'fr',
    publishedYear: 1942,
    pageCount: 184,
    format: PAPERBACK,
    priceCents: 3200,
    stock: 16,
    rating: 4.5,
    reviewCount: 432,
    description: 'An indifferent man commits a crime.',
  },

  {
    title: 'Die Verwandlung',
    author: 'Franz Kafka',
    publisher: 'Reclam',
    genre: 'fiction',
    language: 'de',
    publishedYear: 1915,
    pageCount: 96,
    format: PAPERBACK,
    priceCents: 1900,
    stock: 22,
    rating: 4.4,
    reviewCount: 312,
    description: 'Ein Mensch wird zum Käfer.',
  },
  {
    title: 'Faust I',
    author: 'Johann Wolfgang von Goethe',
    publisher: 'Reclam',
    genre: 'poetry',
    language: 'de',
    publishedYear: 1808,
    pageCount: 222,
    format: PAPERBACK,
    priceCents: 2400,
    stock: 19,
    rating: 4.5,
    reviewCount: 198,
    description: 'Pakt mit dem Teufel.',
  },

  {
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    publisher: 'Sudamericana',
    genre: 'fiction',
    language: 'es',
    publishedYear: 1967,
    pageCount: 432,
    format: PAPERBACK,
    priceCents: 4200,
    stock: 17,
    rating: 4.7,
    reviewCount: 678,
    description: 'La estirpe de los Buendía en Macondo.',
  },

  {
    title: 'Where the Wild Things Are',
    author: 'Maurice Sendak',
    publisher: 'Harper & Row',
    genre: 'children',
    language: 'en',
    publishedYear: 1963,
    pageCount: 48,
    format: HARDCOVER,
    priceCents: 4900,
    stock: 36,
    rating: 4.8,
    reviewCount: 1023,
    description: 'A boy sails to where the wild things are.',
  },
  {
    title: "Charlotte's Web",
    author: 'E.B. White',
    publisher: 'Harper & Row',
    genre: 'children',
    language: 'en',
    publishedYear: 1952,
    pageCount: 192,
    format: PAPERBACK,
    priceCents: 3500,
    stock: 42,
    rating: 4.8,
    reviewCount: 1198,
    description: 'A barn-spider saves a pig.',
  },
  {
    title: 'Akademia Pana Kleksa',
    author: 'Jan Brzechwa',
    publisher: 'Greg',
    genre: 'children',
    language: 'pl',
    publishedYear: 1946,
    pageCount: 256,
    format: PAPERBACK,
    priceCents: 2900,
    stock: 33,
    rating: 4.7,
    reviewCount: 467,
    description: 'Niezwykła szkoła pana Kleksa.',
  },

  {
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    publisher: 'Oxford',
    genre: 'science',
    language: 'en',
    publishedYear: 1976,
    pageCount: 360,
    format: PAPERBACK,
    priceCents: 4900,
    stock: 14,
    rating: 4.6,
    reviewCount: 487,
    description: 'Genes as the unit of natural selection.',
  },
  {
    title: 'Astrophysics for People in a Hurry',
    author: 'Neil deGrasse Tyson',
    publisher: 'Norton',
    genre: 'science',
    language: 'en',
    publishedYear: 2017,
    pageCount: 224,
    format: HARDCOVER,
    priceCents: 5500,
    stock: 21,
    rating: 4.7,
    reviewCount: 678,
    description: 'Cosmic essentials, compactly explained.',
  },
];

function buildCatalogue(): readonly Book[] {
  return SEED.map((entry, index) => {
    const id = `book-${String(index + 1).padStart(3, '0')}`;
    const isbn = `978-0-${String(100_000 + index).padStart(6, '0')}-${index % 10}`;
    return {
      id,
      name: entry.title,
      brand: entry.publisher,
      priceCents: entry.priceCents,
      oldPriceCents: entry.oldPriceCents ?? null,
      imageUrl: `https://picsum.photos/seed/${id}/400/600`,
      description: entry.description,
      stock: entry.stock,
      rating: entry.rating,
      reviewCount: entry.reviewCount,
      category: entry.genre,
      tags: [entry.genre, entry.language, entry.format],
      author: entry.author,
      isbn,
      language: entry.language,
      publishedYear: entry.publishedYear,
      pageCount: entry.pageCount,
      format: entry.format,
    } satisfies Book;
  });
}

export const BOOK_CATALOGUE: readonly Book[] = Object.freeze(buildCatalogue());
