import type { PowerSource, Tool, ToolType } from '../models/tool.js';

// Inline category constants — the lint rule flags strings repeated ≥5 times.
const C_POWER = 'power-tools';
const C_HAND = 'hand-tools';
const C_MEASURING = 'measuring';
const C_SAFETY = 'safety';
const C_FASTENERS = 'fasteners';
const C_STORAGE = 'storage';

interface SeedTool {
  readonly name: string;
  readonly brand: string;
  readonly toolType: ToolType;
  readonly category: string;
  readonly powerSource: PowerSource;
  readonly voltage: number | null;
  readonly weightKg: number;
  readonly warrantyMonths: number;
  readonly priceCents: number;
  readonly oldPriceCents?: number;
  readonly stock: number;
  readonly rating: number;
  readonly reviewCount: number;
  readonly description: string;
}

const SEED: readonly SeedTool[] = [
  // Power tools
  {
    name: 'Wiertarko-wkrętarka 18V',
    brand: 'Bosch',
    toolType: 'drill',
    category: C_POWER,
    powerSource: 'battery',
    voltage: 18,
    weightKg: 1.4,
    warrantyMonths: 24,
    priceCents: 39900,
    oldPriceCents: 45900,
    stock: 27,
    rating: 4.7,
    reviewCount: 423,
    description: 'Kompaktowa wiertarko-wkrętarka akumulatorowa z 2 bateriami i ładowarką.',
  },
  {
    name: 'Wiertarka udarowa 850W',
    brand: 'Makita',
    toolType: 'drill',
    category: C_POWER,
    powerSource: 'corded',
    voltage: 230,
    weightKg: 2.4,
    warrantyMonths: 36,
    priceCents: 32900,
    stock: 18,
    rating: 4.6,
    reviewCount: 287,
    description: 'Solidna wiertarka udarowa do betonu i muru.',
  },
  {
    name: 'Wiertarka SDS-Plus 800W',
    brand: 'DeWalt',
    toolType: 'drill',
    category: C_POWER,
    powerSource: 'corded',
    voltage: 230,
    weightKg: 3.1,
    warrantyMonths: 36,
    priceCents: 58900,
    stock: 12,
    rating: 4.8,
    reviewCount: 156,
    description: 'Profesjonalny młotowiertarka SDS-Plus, 3 tryby pracy.',
  },
  {
    name: 'Wkrętarka udarowa 18V',
    brand: 'Milwaukee',
    toolType: 'screwdriver',
    category: C_POWER,
    powerSource: 'battery',
    voltage: 18,
    weightKg: 1.6,
    warrantyMonths: 24,
    priceCents: 79900,
    stock: 9,
    rating: 4.9,
    reviewCount: 312,
    description: 'Wkrętarka udarowa M18 Fuel z bezszczotkowym silnikiem.',
  },
  {
    name: 'Pilarka tarczowa 1400W',
    brand: 'Bosch',
    toolType: 'saw',
    category: C_POWER,
    powerSource: 'corded',
    voltage: 230,
    weightKg: 3.9,
    warrantyMonths: 24,
    priceCents: 49900,
    stock: 14,
    rating: 4.5,
    reviewCount: 198,
    description: 'Pilarka tarczowa do drewna, tarcza 190mm.',
  },
  {
    name: 'Wyrzynarka 720W',
    brand: 'Makita',
    toolType: 'saw',
    category: C_POWER,
    powerSource: 'corded',
    voltage: 230,
    weightKg: 2.5,
    warrantyMonths: 36,
    priceCents: 35900,
    stock: 21,
    rating: 4.6,
    reviewCount: 245,
    description: 'Wyrzynarka do drewna, metalu i plastiku.',
  },
  {
    name: 'Pilarka łańcuchowa 36V',
    brand: 'Stihl',
    toolType: 'saw',
    category: C_POWER,
    powerSource: 'battery',
    voltage: 36,
    weightKg: 2.9,
    warrantyMonths: 24,
    priceCents: 119900,
    stock: 6,
    rating: 4.8,
    reviewCount: 89,
    description: 'Akumulatorowa pilarka łańcuchowa MSA 220 C-B.',
  },
  {
    name: 'Szlifierka kątowa 125mm',
    brand: 'Makita',
    toolType: 'grinder',
    category: C_POWER,
    powerSource: 'corded',
    voltage: 230,
    weightKg: 2.2,
    warrantyMonths: 36,
    priceCents: 27900,
    oldPriceCents: 32900,
    stock: 33,
    rating: 4.7,
    reviewCount: 412,
    description: 'Szlifierka kątowa 720W z regulacją obrotów.',
  },
  {
    name: 'Szlifierka kątowa 230mm',
    brand: 'Bosch',
    toolType: 'grinder',
    category: C_POWER,
    powerSource: 'corded',
    voltage: 230,
    weightKg: 5.4,
    warrantyMonths: 24,
    priceCents: 49900,
    stock: 11,
    rating: 4.6,
    reviewCount: 167,
    description: 'Profesjonalna szlifierka kątowa 2200W.',
  },
  {
    name: 'Szlifierka oscylacyjna',
    brand: 'Bosch',
    toolType: 'sander',
    category: C_POWER,
    powerSource: 'corded',
    voltage: 230,
    weightKg: 1.6,
    warrantyMonths: 24,
    priceCents: 24900,
    stock: 26,
    rating: 4.5,
    reviewCount: 198,
    description: 'Szlifierka oscylacyjna do wykończeniowych prac z drewnem.',
  },
  {
    name: 'Szlifierka mimośrodowa',
    brand: 'Festool',
    toolType: 'sander',
    category: C_POWER,
    powerSource: 'corded',
    voltage: 230,
    weightKg: 1.3,
    warrantyMonths: 36,
    priceCents: 109900,
    stock: 7,
    rating: 4.9,
    reviewCount: 78,
    description: 'Profesjonalna szlifierka ETS EC 125 z odpylaczem.',
  },

  // Hand tools
  {
    name: 'Zestaw wkrętaków precyzyjnych',
    brand: 'Wera',
    toolType: 'screwdriver',
    category: C_HAND,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.4,
    warrantyMonths: 60,
    priceCents: 14900,
    stock: 45,
    rating: 4.8,
    reviewCount: 567,
    description: 'Komplet 24 wkrętaków precyzyjnych Kraftform Micro.',
  },
  {
    name: 'Zestaw wkrętaków 8 szt.',
    brand: 'Stanley',
    toolType: 'screwdriver',
    category: C_HAND,
    powerSource: 'manual',
    voltage: null,
    weightKg: 1.1,
    warrantyMonths: 12,
    priceCents: 7900,
    stock: 62,
    rating: 4.4,
    reviewCount: 312,
    description: 'Zestaw 8 wkrętaków FatMax (płaskie + krzyżakowe).',
  },
  {
    name: 'Klucz nastawny 250mm',
    brand: 'Bahco',
    toolType: 'wrench',
    category: C_HAND,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.5,
    warrantyMonths: 60,
    priceCents: 12900,
    stock: 38,
    rating: 4.7,
    reviewCount: 234,
    description: 'Klucz nastawny Bahco 9031 z ergonomicznym uchwytem.',
  },
  {
    name: 'Zestaw kluczy nasadowych 1/2"',
    brand: 'Wera',
    toolType: 'wrench',
    category: C_HAND,
    powerSource: 'manual',
    voltage: null,
    weightKg: 4.2,
    warrantyMonths: 60,
    priceCents: 89900,
    stock: 8,
    rating: 4.9,
    reviewCount: 145,
    description: 'Komplet 28 kluczy nasadowych w organizerze.',
  },
  {
    name: 'Młotek ślusarski 500g',
    brand: 'Stanley',
    toolType: 'hammer',
    category: C_HAND,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.6,
    warrantyMonths: 12,
    priceCents: 4900,
    stock: 71,
    rating: 4.4,
    reviewCount: 245,
    description: 'Stalowy młotek ślusarski z włóknistym trzonkiem.',
  },
  {
    name: 'Młotek murarski 800g',
    brand: 'Bahco',
    toolType: 'hammer',
    category: C_HAND,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.9,
    warrantyMonths: 36,
    priceCents: 8900,
    stock: 22,
    rating: 4.6,
    reviewCount: 134,
    description: 'Kuty młotek murarski z trzonkiem hikorowym.',
  },

  // Measuring
  {
    name: 'Miara zwijana 5m',
    brand: 'Stanley',
    toolType: 'measuring',
    category: C_MEASURING,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.3,
    warrantyMonths: 36,
    priceCents: 3900,
    stock: 84,
    rating: 4.5,
    reviewCount: 421,
    description: 'Stalowa miara zwijana FatMax 5m × 25mm.',
  },
  {
    name: 'Dalmierz laserowy 50m',
    brand: 'Bosch',
    toolType: 'measuring',
    category: C_MEASURING,
    powerSource: 'battery',
    voltage: 3,
    weightKg: 0.1,
    warrantyMonths: 24,
    priceCents: 24900,
    oldPriceCents: 29900,
    stock: 23,
    rating: 4.7,
    reviewCount: 312,
    description: 'Dalmierz laserowy GLM 50-22 z dokładnością ±2 mm.',
  },
  {
    name: 'Poziomica 60cm',
    brand: 'Stabila',
    toolType: 'measuring',
    category: C_MEASURING,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.5,
    warrantyMonths: 24,
    priceCents: 9900,
    stock: 31,
    rating: 4.8,
    reviewCount: 167,
    description: 'Aluminiowa poziomica typu 96-2.',
  },
  {
    name: 'Suwmiarka cyfrowa 150mm',
    brand: 'Mitutoyo',
    toolType: 'measuring',
    category: C_MEASURING,
    powerSource: 'battery',
    voltage: 1,
    weightKg: 0.2,
    warrantyMonths: 24,
    priceCents: 49900,
    stock: 14,
    rating: 4.9,
    reviewCount: 198,
    description: 'Profesjonalna suwmiarka cyfrowa Mitutoyo serii 500.',
  },

  // Safety
  {
    name: 'Okulary ochronne BHP',
    brand: '3M',
    toolType: 'safety',
    category: C_SAFETY,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.1,
    warrantyMonths: 12,
    priceCents: 1900,
    stock: 122,
    rating: 4.4,
    reviewCount: 543,
    description: 'Okulary ochronne 3M SecureFit przeciwodpryskowe.',
  },
  {
    name: 'Rękawice robocze (10 par)',
    brand: 'Stanley',
    toolType: 'safety',
    category: C_SAFETY,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.6,
    warrantyMonths: 6,
    priceCents: 4900,
    stock: 67,
    rating: 4.3,
    reviewCount: 312,
    description: 'Komplet 10 par rękawic powlekanych nitrylem.',
  },
  {
    name: 'Maska przeciwpyłowa FFP3',
    brand: '3M',
    toolType: 'safety',
    category: C_SAFETY,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.0,
    warrantyMonths: 6,
    priceCents: 2900,
    stock: 198,
    rating: 4.6,
    reviewCount: 234,
    description: 'Maska przeciwpyłowa 3M 8835+ klasy FFP3.',
  },
  {
    name: 'Hełm ochronny budowlany',
    brand: 'Uvex',
    toolType: 'safety',
    category: C_SAFETY,
    powerSource: 'manual',
    voltage: null,
    weightKg: 0.4,
    warrantyMonths: 12,
    priceCents: 8900,
    stock: 28,
    rating: 4.5,
    reviewCount: 156,
    description: 'Hełm ochronny Uvex Pheos z systemem regulacji.',
  },

  // Storage / fasteners
  {
    name: 'Skrzynka narzędziowa 22"',
    brand: 'Stanley',
    toolType: 'safety',
    category: C_STORAGE,
    powerSource: 'manual',
    voltage: null,
    weightKg: 2.4,
    warrantyMonths: 24,
    priceCents: 12900,
    stock: 18,
    rating: 4.5,
    reviewCount: 198,
    description: 'Skrzynka narzędziowa FatMax z metalowymi zatrzaskami.',
  },
  {
    name: 'Zestaw wkrętów 2200 szt.',
    brand: 'Wkret-Met',
    toolType: 'screwdriver',
    category: C_FASTENERS,
    powerSource: 'manual',
    voltage: null,
    weightKg: 4.8,
    warrantyMonths: 12,
    priceCents: 17900,
    oldPriceCents: 22900,
    stock: 24,
    rating: 4.4,
    reviewCount: 156,
    description: 'Mega-zestaw wkrętów drewnianych w organizerze.',
  },
];

function buildCatalogue(): readonly Tool[] {
  return SEED.map((entry, index) => {
    const id = `tool-${String(index + 1).padStart(3, '0')}`;
    return {
      id,
      name: entry.name,
      brand: entry.brand,
      priceCents: entry.priceCents,
      oldPriceCents: entry.oldPriceCents ?? null,
      imageUrl: `https://picsum.photos/seed/${id}/600/600`,
      description: entry.description,
      stock: entry.stock,
      rating: entry.rating,
      reviewCount: entry.reviewCount,
      category: entry.category,
      tags: [entry.category, entry.toolType, entry.powerSource],
      toolType: entry.toolType,
      powerSource: entry.powerSource,
      voltage: entry.voltage,
      weightKg: entry.weightKg,
      warrantyMonths: entry.warrantyMonths,
      skuCode: `TS-${id.toUpperCase()}`,
    } satisfies Tool;
  });
}

export const TOOL_CATALOGUE: readonly Tool[] = Object.freeze(buildCatalogue());
