import type { AgeGroup, GenderHint, Toy } from '../models/toy.js';

interface SeedToy {
  readonly name: string;
  readonly brand: string;
  readonly category: string;
  readonly ageGroup: AgeGroup;
  readonly minAge: number;
  readonly maxAge: number;
  readonly pieceCount: number | null;
  readonly genderHint: GenderHint;
  readonly batteryRequired: boolean;
  readonly safetyCertified: boolean;
  readonly priceCents: number;
  readonly oldPriceCents?: number;
  readonly stock: number;
  readonly rating: number;
  readonly reviewCount: number;
  readonly description: string;
}

const SEED: readonly SeedToy[] = [
  // Building blocks
  {
    name: 'Lego Classic Kreatywne Klocki',
    brand: 'Lego',
    category: 'building',
    ageGroup: '3-5',
    minAge: 4,
    maxAge: 99,
    pieceCount: 484,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 13900,
    oldPriceCents: 15900,
    stock: 42,
    rating: 4.8,
    reviewCount: 1023,
    description: 'Klasyczny zestaw 484 elementów do swobodnej zabawy.',
  },
  {
    name: 'Lego City Posterunek policji',
    brand: 'Lego',
    category: 'building',
    ageGroup: '6-8',
    minAge: 6,
    maxAge: 12,
    pieceCount: 668,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 39900,
    stock: 18,
    rating: 4.7,
    reviewCount: 412,
    description: 'Posterunek policji z 7 minifigurkami i pojazdami.',
  },
  {
    name: 'Lego Technic Bugatti Chiron',
    brand: 'Lego',
    category: 'building',
    ageGroup: '13+',
    minAge: 16,
    maxAge: 99,
    pieceCount: 3599,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 169900,
    stock: 4,
    rating: 4.9,
    reviewCount: 234,
    description: 'Kolekcjonerski model Bugatti Chiron w skali 1:8.',
  },
  {
    name: 'Mega Bloks Wagon Kolejki',
    brand: 'Mega Bloks',
    category: 'building',
    ageGroup: '0-2',
    minAge: 1,
    maxAge: 5,
    pieceCount: 50,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 8900,
    stock: 28,
    rating: 4.5,
    reviewCount: 198,
    description: 'Wielkogabarytowe klocki do zabawy dla najmłodszych.',
  },
  {
    name: 'Magformers 30 elementów',
    brand: 'Magformers',
    category: 'building',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 8,
    pieceCount: 30,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 22900,
    stock: 15,
    rating: 4.7,
    reviewCount: 312,
    description: 'Magnetyczne klocki konstrukcyjne — 30 elementów.',
  },

  // Dolls
  {
    name: 'Barbie Dreamhouse',
    brand: 'Mattel',
    category: 'dolls',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 8,
    pieceCount: 70,
    genderHint: 'girls',
    batteryRequired: true,
    safetyCertified: true,
    priceCents: 89900,
    oldPriceCents: 99900,
    stock: 7,
    rating: 4.8,
    reviewCount: 567,
    description: 'Trzypiętrowy domek Barbie z 70 akcesoriami.',
  },
  {
    name: 'Barbie Lekarka',
    brand: 'Mattel',
    category: 'dolls',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 10,
    pieceCount: 1,
    genderHint: 'girls',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 4900,
    stock: 41,
    rating: 4.6,
    reviewCount: 287,
    description: 'Lalka Barbie w wersji "Doctor" z fartuchem i stetoskopem.',
  },
  {
    name: 'Lalka L.O.L. Surprise',
    brand: 'MGA',
    category: 'dolls',
    ageGroup: '6-8',
    minAge: 6,
    maxAge: 12,
    pieceCount: 7,
    genderHint: 'girls',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 5900,
    stock: 32,
    rating: 4.5,
    reviewCount: 234,
    description: 'Niespodzianka z 7 elementami do odkrycia.',
  },

  // Vehicles
  {
    name: 'Hot Wheels Tor Looping',
    brand: 'Mattel',
    category: 'vehicles',
    ageGroup: '3-5',
    minAge: 4,
    maxAge: 10,
    pieceCount: 50,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 14900,
    stock: 36,
    rating: 4.6,
    reviewCount: 423,
    description: 'Tor wyścigowy z looping i dwoma samochodzikami.',
  },
  {
    name: 'Auto zdalnie sterowane 1:18',
    brand: 'Carrera',
    category: 'vehicles',
    ageGroup: '6-8',
    minAge: 6,
    maxAge: 99,
    pieceCount: 1,
    genderHint: 'any',
    batteryRequired: true,
    safetyCertified: true,
    priceCents: 24900,
    stock: 19,
    rating: 4.5,
    reviewCount: 187,
    description: 'Wyścigowy samochód RC zasięg do 30 metrów.',
  },
  {
    name: 'Pojazd Strażacki Brio',
    brand: 'Brio',
    category: 'vehicles',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 8,
    pieceCount: 8,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 12900,
    stock: 24,
    rating: 4.7,
    reviewCount: 156,
    description: 'Drewniany pojazd strażacki Brio.',
  },

  // Plush
  {
    name: 'Pluszowy Miś 60cm',
    brand: 'Steiff',
    category: 'plush',
    ageGroup: '0-2',
    minAge: 0,
    maxAge: 99,
    pieceCount: 1,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 12900,
    stock: 22,
    rating: 4.9,
    reviewCount: 312,
    description: 'Klasyczny pluszowy miś Steiff z certyfikatem CE.',
  },
  {
    name: 'Maskotka Jednorożec',
    brand: 'Ty',
    category: 'plush',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 99,
    pieceCount: 1,
    genderHint: 'girls',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 3900,
    stock: 56,
    rating: 4.7,
    reviewCount: 412,
    description: 'Tęczowy jednorożec o miękkim futerku.',
  },
  {
    name: 'Pluszowy Dinozaur T-Rex',
    brand: 'Ty',
    category: 'plush',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 99,
    pieceCount: 1,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 4500,
    stock: 38,
    rating: 4.6,
    reviewCount: 198,
    description: 'Pluszowy Tyrannosaurus Rex w zielonym kolorze.',
  },

  // Board games
  {
    name: 'Monopoly Polska',
    brand: 'Hasbro',
    category: 'board-games',
    ageGroup: '9-12',
    minAge: 8,
    maxAge: 99,
    pieceCount: 100,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 13900,
    stock: 28,
    rating: 4.6,
    reviewCount: 567,
    description: 'Polska wersja klasycznej gry Monopoly.',
  },
  {
    name: 'Catan',
    brand: 'Asmodee',
    category: 'board-games',
    ageGroup: '9-12',
    minAge: 10,
    maxAge: 99,
    pieceCount: 200,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 16900,
    oldPriceCents: 19900,
    stock: 17,
    rating: 4.8,
    reviewCount: 678,
    description: 'Klasyczna gra strategiczna o budowaniu osad.',
  },
  {
    name: 'Carcassonne',
    brand: 'Asmodee',
    category: 'board-games',
    ageGroup: '6-8',
    minAge: 7,
    maxAge: 99,
    pieceCount: 84,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 12900,
    stock: 22,
    rating: 4.7,
    reviewCount: 412,
    description: 'Gra w średniowiecznej Francji o układaniu mapy.',
  },

  // Puzzles
  {
    name: 'Puzzle Mapa Świata 1000 el.',
    brand: 'Trefl',
    category: 'puzzles',
    ageGroup: '9-12',
    minAge: 10,
    maxAge: 99,
    pieceCount: 1000,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 4900,
    stock: 33,
    rating: 4.6,
    reviewCount: 287,
    description: 'Klasyczne puzzle mapy świata.',
  },
  {
    name: 'Puzzle Mikołaj 60 el.',
    brand: 'Trefl',
    category: 'puzzles',
    ageGroup: '3-5',
    minAge: 4,
    maxAge: 8,
    pieceCount: 60,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 1900,
    stock: 67,
    rating: 4.5,
    reviewCount: 198,
    description: 'Puzzle z Świętym Mikołajem dla najmłodszych.',
  },

  // Arts & crafts
  {
    name: 'Zestaw Plastelina 24 kolory',
    brand: 'Play-Doh',
    category: 'arts-crafts',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 10,
    pieceCount: 24,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 4900,
    stock: 46,
    rating: 4.7,
    reviewCount: 412,
    description: 'Klasyczna plastelina Play-Doh w 24 kolorach.',
  },
  {
    name: 'Zestaw kredek 64 szt.',
    brand: 'Crayola',
    category: 'arts-crafts',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 12,
    pieceCount: 64,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 3900,
    stock: 78,
    rating: 4.6,
    reviewCount: 312,
    description: 'Kredki wodne Crayola w pudełku z temperówką.',
  },

  // Outdoor
  {
    name: 'Hulajnoga 3-kołowa',
    brand: 'Razor',
    category: 'outdoor',
    ageGroup: '3-5',
    minAge: 3,
    maxAge: 8,
    pieceCount: 1,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 16900,
    stock: 14,
    rating: 4.5,
    reviewCount: 234,
    description: 'Stabilna 3-kołowa hulajnoga dla najmłodszych.',
  },
  {
    name: 'Rowerek biegowy',
    brand: 'Strider',
    category: 'outdoor',
    ageGroup: '0-2',
    minAge: 2,
    maxAge: 5,
    pieceCount: 1,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 39900,
    stock: 9,
    rating: 4.8,
    reviewCount: 156,
    description: 'Rowerek biegowy bez pedałów dla maluchów.',
  },

  // Educational
  {
    name: 'Mikroskop dziecięcy 600x',
    brand: 'National Geographic',
    category: 'educational',
    ageGroup: '9-12',
    minAge: 8,
    maxAge: 14,
    pieceCount: 20,
    genderHint: 'any',
    batteryRequired: true,
    safetyCertified: true,
    priceCents: 24900,
    stock: 12,
    rating: 4.6,
    reviewCount: 187,
    description: 'Mikroskop z akcesoriami i preparatami.',
  },
  {
    name: 'Zestaw eksperymentów chemicznych',
    brand: 'Clementoni',
    category: 'educational',
    ageGroup: '9-12',
    minAge: 10,
    maxAge: 14,
    pieceCount: 80,
    genderHint: 'any',
    batteryRequired: false,
    safetyCertified: true,
    priceCents: 14900,
    stock: 18,
    rating: 4.7,
    reviewCount: 312,
    description: 'Bezpieczny zestaw 80 eksperymentów chemicznych.',
  },
  {
    name: 'Globus podświetlany',
    brand: 'Ravensburger',
    category: 'educational',
    ageGroup: '6-8',
    minAge: 6,
    maxAge: 14,
    pieceCount: 1,
    genderHint: 'any',
    batteryRequired: true,
    safetyCertified: true,
    priceCents: 16900,
    stock: 14,
    rating: 4.7,
    reviewCount: 198,
    description: 'Globus z mapą polityczną w dzień i fizyczną po podświetleniu.',
  },
];

function buildCatalogue(): readonly Toy[] {
  return SEED.map((entry, index) => {
    const id = `toy-${String(index + 1).padStart(3, '0')}`;
    return {
      id,
      name: entry.name,
      brand: entry.brand,
      priceCents: entry.priceCents,
      oldPriceCents: entry.oldPriceCents ?? null,
      imageUrl: `https://picsum.photos/seed/${id}/600/600`,
      description: entry.description,
      stock: entry.stock,
      rating: entry.rating,
      reviewCount: entry.reviewCount,
      category: entry.category,
      tags: [entry.category, entry.ageGroup, entry.genderHint],
      ageGroup: entry.ageGroup,
      minAge: entry.minAge,
      maxAge: entry.maxAge,
      pieceCount: entry.pieceCount,
      genderHint: entry.genderHint,
      batteryRequired: entry.batteryRequired,
      safetyCertified: entry.safetyCertified,
    } satisfies Toy;
  });
}

export const TOY_CATALOGUE: readonly Toy[] = Object.freeze(buildCatalogue());
