import type { Book, BookGenre, BookLanguage } from '../models/book.js';
import type { Loan, Reservation } from '../models/loan.js';
import type { Member } from '../models/member.js';

interface BookSeed {
  readonly title: string;
  readonly author: string;
  readonly genre: BookGenre;
  readonly language: BookLanguage;
  readonly publishedYear: number;
  readonly totalCopies: number;
  readonly blurb: string;
}

// 60 well-known titles. Genre / language / year are realistic but not strict.
const BOOK_SEEDS: readonly BookSeed[] = [
  {
    title: 'Pan Tadeusz',
    author: 'Adam Mickiewicz',
    genre: 'poetry',
    language: 'pl',
    publishedYear: 1834,
    totalCopies: 4,
    blurb: 'Klasyczna epopeja narodowa.',
  },
  {
    title: 'Lalka',
    author: 'Bolesław Prus',
    genre: 'fiction',
    language: 'pl',
    publishedYear: 1890,
    totalCopies: 3,
    blurb: 'Powieść panoramiczna o Wokulskim i Łęckiej.',
  },
  {
    title: 'Ferdydurke',
    author: 'Witold Gombrowicz',
    genre: 'fiction',
    language: 'pl',
    publishedYear: 1937,
    totalCopies: 2,
    blurb: 'Groteskowy debiut o niedojrzałości.',
  },
  {
    title: 'Solaris',
    author: 'Stanisław Lem',
    genre: 'sci-fi',
    language: 'pl',
    publishedYear: 1961,
    totalCopies: 5,
    blurb: 'Stacja badawcza nad świadomą planetą.',
  },
  {
    title: 'Bajki robotów',
    author: 'Stanisław Lem',
    genre: 'sci-fi',
    language: 'pl',
    publishedYear: 1964,
    totalCopies: 3,
    blurb: 'Cykl baśniowych opowieści cybernetycznych.',
  },
  {
    title: 'Cyberiada',
    author: 'Stanisław Lem',
    genre: 'sci-fi',
    language: 'pl',
    publishedYear: 1965,
    totalCopies: 2,
    blurb: 'Eksperymenty Trurla i Klapaucjusza.',
  },
  {
    title: 'Wiedźmin: Ostatnie życzenie',
    author: 'Andrzej Sapkowski',
    genre: 'fantasy',
    language: 'pl',
    publishedYear: 1993,
    totalCopies: 6,
    blurb: 'Pierwszy zbiór opowiadań o Geralcie z Rivii.',
  },
  {
    title: 'Wiedźmin: Krew elfów',
    author: 'Andrzej Sapkowski',
    genre: 'fantasy',
    language: 'pl',
    publishedYear: 1994,
    totalCopies: 4,
    blurb: 'Pierwsza pełnowymiarowa powieść sagi.',
  },
  {
    title: 'Mistrz i Małgorzata',
    author: 'Michaił Bułhakow',
    genre: 'fiction',
    language: 'pl',
    publishedYear: 1967,
    totalCopies: 3,
    blurb: 'Surrealistyczna powieść o diable w Moskwie.',
  },
  {
    title: 'Zbrodnia i kara',
    author: 'Fiodor Dostojewski',
    genre: 'fiction',
    language: 'pl',
    publishedYear: 1866,
    totalCopies: 4,
    blurb: 'Psychologiczna analiza zbrodni i pokuty.',
  },

  {
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1954,
    totalCopies: 5,
    blurb: 'Epic quest to destroy the One Ring.',
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1937,
    totalCopies: 4,
    blurb: "Bilbo's unexpected journey.",
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: 'J.K. Rowling',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1997,
    totalCopies: 7,
    blurb: 'A boy discovers he is a wizard.',
  },
  {
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1998,
    totalCopies: 5,
    blurb: 'The Chamber of Secrets has been opened.',
  },
  {
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: 'J.K. Rowling',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1999,
    totalCopies: 5,
    blurb: 'Sirius Black has escaped.',
  },
  {
    title: 'A Game of Thrones',
    author: 'George R.R. Martin',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1996,
    totalCopies: 4,
    blurb: 'Houses scheme as winter approaches.',
  },
  {
    title: 'A Clash of Kings',
    author: 'George R.R. Martin',
    genre: 'fantasy',
    language: 'en',
    publishedYear: 1998,
    totalCopies: 3,
    blurb: 'Five kings claim the Iron Throne.',
  },
  {
    title: 'Foundation',
    author: 'Isaac Asimov',
    genre: 'sci-fi',
    language: 'en',
    publishedYear: 1951,
    totalCopies: 3,
    blurb: "Psychohistory predicts the empire's fall.",
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    genre: 'sci-fi',
    language: 'en',
    publishedYear: 1965,
    totalCopies: 4,
    blurb: 'Spice and power on desert planet Arrakis.',
  },
  {
    title: 'Neuromancer',
    author: 'William Gibson',
    genre: 'sci-fi',
    language: 'en',
    publishedYear: 1984,
    totalCopies: 2,
    blurb: 'Cyberpunk classic that named cyberspace.',
  },

  {
    title: '1984',
    author: 'George Orwell',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1949,
    totalCopies: 5,
    blurb: 'Dystopian critique of totalitarianism.',
  },
  {
    title: 'Animal Farm',
    author: 'George Orwell',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1945,
    totalCopies: 4,
    blurb: 'Allegorical farm where pigs take over.',
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1932,
    totalCopies: 3,
    blurb: 'Engineered happiness in a future society.',
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1813,
    totalCopies: 4,
    blurb: 'Bennet sisters navigate love and class.',
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1960,
    totalCopies: 4,
    blurb: 'Justice and racism in 1930s Alabama.',
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1925,
    totalCopies: 3,
    blurb: 'Jazz Age dreams and disillusionment.',
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1951,
    totalCopies: 3,
    blurb: 'Teen angst with Holden Caulfield.',
  },
  {
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1967,
    totalCopies: 3,
    blurb: 'Magical-realist saga of the Buendía family.',
  },
  {
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1866,
    totalCopies: 3,
    blurb: "A student's guilt after a murder.",
  },
  {
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    genre: 'fiction',
    language: 'en',
    publishedYear: 1869,
    totalCopies: 2,
    blurb: 'Russian families during Napoleonic wars.',
  },

  {
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    genre: 'non-fiction',
    language: 'en',
    publishedYear: 2011,
    totalCopies: 6,
    blurb: 'A brief history of humankind.',
  },
  {
    title: 'Homo Deus',
    author: 'Yuval Noah Harari',
    genre: 'non-fiction',
    language: 'en',
    publishedYear: 2015,
    totalCopies: 4,
    blurb: 'Where do we go from here?',
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    genre: 'non-fiction',
    language: 'en',
    publishedYear: 2011,
    totalCopies: 5,
    blurb: 'Two systems of human thought.',
  },
  {
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    genre: 'science',
    language: 'en',
    publishedYear: 1976,
    totalCopies: 3,
    blurb: 'Genes as the unit of natural selection.',
  },
  {
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    genre: 'science',
    language: 'en',
    publishedYear: 1988,
    totalCopies: 4,
    blurb: 'Cosmology for everyone.',
  },
  {
    title: 'The Origin of Species',
    author: 'Charles Darwin',
    genre: 'science',
    language: 'en',
    publishedYear: 1859,
    totalCopies: 2,
    blurb: 'Foundational work on evolution.',
  },
  {
    title: 'Cosmos',
    author: 'Carl Sagan',
    genre: 'science',
    language: 'en',
    publishedYear: 1980,
    totalCopies: 3,
    blurb: 'A personal voyage through the universe.',
  },
  {
    title: 'Astrophysics for People in a Hurry',
    author: 'Neil deGrasse Tyson',
    genre: 'science',
    language: 'en',
    publishedYear: 2017,
    totalCopies: 4,
    blurb: 'Cosmic essentials, compactly explained.',
  },

  {
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    genre: 'biography',
    language: 'en',
    publishedYear: 2011,
    totalCopies: 4,
    blurb: 'Authorised biography of the Apple co-founder.',
  },
  {
    title: 'Long Walk to Freedom',
    author: 'Nelson Mandela',
    genre: 'biography',
    language: 'en',
    publishedYear: 1994,
    totalCopies: 3,
    blurb: "Mandela's autobiography.",
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    genre: 'biography',
    language: 'en',
    publishedYear: 2018,
    totalCopies: 4,
    blurb: 'Memoir of self-education against the odds.',
  },
  {
    title: 'Becoming',
    author: 'Michelle Obama',
    genre: 'biography',
    language: 'en',
    publishedYear: 2018,
    totalCopies: 5,
    blurb: 'Memoir of the former First Lady.',
  },

  {
    title: 'The Silk Roads',
    author: 'Peter Frankopan',
    genre: 'history',
    language: 'en',
    publishedYear: 2015,
    totalCopies: 3,
    blurb: 'A new history of the world.',
  },
  {
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    genre: 'history',
    language: 'en',
    publishedYear: 1997,
    totalCopies: 3,
    blurb: 'Geography shapes civilizations.',
  },
  {
    title: 'The Wright Brothers',
    author: 'David McCullough',
    genre: 'history',
    language: 'en',
    publishedYear: 2015,
    totalCopies: 2,
    blurb: 'The men who launched the airplane.',
  },

  {
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    genre: 'mystery',
    language: 'en',
    publishedYear: 2005,
    totalCopies: 4,
    blurb: 'A journalist and a hacker probe a vanished heiress.',
  },
  {
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    genre: 'mystery',
    language: 'en',
    publishedYear: 2003,
    totalCopies: 5,
    blurb: 'A symbologist races to solve a murder.',
  },
  {
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    genre: 'mystery',
    language: 'en',
    publishedYear: 2012,
    totalCopies: 3,
    blurb: 'Marriage gone darkly wrong.',
  },

  {
    title: 'Where the Wild Things Are',
    author: 'Maurice Sendak',
    genre: 'children',
    language: 'en',
    publishedYear: 1963,
    totalCopies: 5,
    blurb: 'A boy sails to where the wild things are.',
  },
  {
    title: "Charlotte's Web",
    author: 'E.B. White',
    genre: 'children',
    language: 'en',
    publishedYear: 1952,
    totalCopies: 4,
    blurb: 'A barn-spider saves a pig.',
  },
  {
    title: 'Matilda',
    author: 'Roald Dahl',
    genre: 'children',
    language: 'en',
    publishedYear: 1988,
    totalCopies: 5,
    blurb: 'A brilliant girl with quiet powers.',
  },
  {
    title: 'Akademia Pana Kleksa',
    author: 'Jan Brzechwa',
    genre: 'children',
    language: 'pl',
    publishedYear: 1946,
    totalCopies: 4,
    blurb: 'Niezwykła szkoła pana Kleksa.',
  },

  {
    title: 'Le Petit Prince',
    author: 'Antoine de Saint-Exupéry',
    genre: 'fiction',
    language: 'fr',
    publishedYear: 1943,
    totalCopies: 4,
    blurb: 'A pilot meets a young prince in the desert.',
  },
  {
    title: 'Les Misérables',
    author: 'Victor Hugo',
    genre: 'fiction',
    language: 'fr',
    publishedYear: 1862,
    totalCopies: 2,
    blurb: 'Redemption and revolution in 19th-century France.',
  },
  {
    title: "L'Étranger",
    author: 'Albert Camus',
    genre: 'fiction',
    language: 'fr',
    publishedYear: 1942,
    totalCopies: 3,
    blurb: 'An indifferent man commits a crime.',
  },

  {
    title: 'Die Verwandlung',
    author: 'Franz Kafka',
    genre: 'fiction',
    language: 'de',
    publishedYear: 1915,
    totalCopies: 2,
    blurb: 'Ein Mensch wird zum Käfer.',
  },
  {
    title: 'Faust',
    author: 'Johann Wolfgang von Goethe',
    genre: 'fiction',
    language: 'de',
    publishedYear: 1808,
    totalCopies: 2,
    blurb: 'Pakt mit dem Teufel.',
  },
  {
    title: 'Der Steppenwolf',
    author: 'Hermann Hesse',
    genre: 'fiction',
    language: 'de',
    publishedYear: 1927,
    totalCopies: 2,
    blurb: 'Innere Zerrissenheit eines Außenseiters.',
  },

  {
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    genre: 'fiction',
    language: 'es',
    publishedYear: 1967,
    totalCopies: 2,
    blurb: 'La estirpe de los Buendía en Macondo.',
  },
  {
    title: 'La sombra del viento',
    author: 'Carlos Ruiz Zafón',
    genre: 'mystery',
    language: 'es',
    publishedYear: 2001,
    totalCopies: 3,
    blurb: 'Un libro maldito en la Barcelona de postguerra.',
  },
];

function buildBooks(): readonly Book[] {
  return BOOK_SEEDS.map((seed, index) => {
    const id = `book-${String(index + 1).padStart(3, '0')}`;
    const isbn = `978-83-${String(10_000 + index).padStart(5, '0')}-${index % 10}`;
    return {
      id,
      title: seed.title,
      author: seed.author,
      isbn,
      genre: seed.genre,
      language: seed.language,
      publishedYear: seed.publishedYear,
      coverUrl: `https://picsum.photos/seed/${id}/240/360`,
      blurb: seed.blurb,
      totalCopies: seed.totalCopies,
    } satisfies Book;
  });
}

export const BOOK_CATALOGUE: readonly Book[] = Object.freeze(buildBooks());

export const MEMBERS: readonly Member[] = Object.freeze([
  {
    id: 'member-reader-1',
    firstName: 'Anna',
    lastName: 'Nowak',
    role: 'reader',
    email: 'anna.nowak@example.com',
    cardNumber: 'R-0001',
  },
  {
    id: 'member-reader-2',
    firstName: 'Jan',
    lastName: 'Kowalski',
    role: 'reader',
    email: 'jan.kowalski@example.com',
    cardNumber: 'R-0002',
  },
  {
    id: 'member-reader-3',
    firstName: 'Maria',
    lastName: 'Wiśniewska',
    role: 'reader',
    email: 'maria.w@example.com',
    cardNumber: 'R-0003',
  },
  {
    id: 'member-reader-4',
    firstName: 'Piotr',
    lastName: 'Zieliński',
    role: 'reader',
    email: 'piotr.z@example.com',
    cardNumber: 'R-0004',
  },
  {
    id: 'member-librarian-1',
    firstName: 'Ewa',
    lastName: 'Lewandowska',
    role: 'librarian',
    email: 'ewa.l@example.com',
    cardNumber: 'L-0001',
  },
]);

/** A few baseline loans + reservations so the demo isn't empty on first load. */
const TODAY = '2026-05-18';
function daysAgo(days: number): string {
  const d = new Date(TODAY);
  d.setDate(d.getDate() - days);
  return d.toISOString().slice(0, 10);
}
function daysFromNow(days: number): string {
  const d = new Date(TODAY);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const LOANS: readonly Loan[] = Object.freeze([
  {
    id: 'loan-0001',
    bookId: 'book-001',
    memberId: 'member-reader-1',
    issuedAt: daysAgo(5),
    dueDate: daysFromNow(9),
    returnedAt: null,
    status: 'active',
    renewals: 0,
  },
  {
    id: 'loan-0002',
    bookId: 'book-007',
    memberId: 'member-reader-2',
    issuedAt: daysAgo(20),
    dueDate: daysAgo(6),
    returnedAt: null,
    status: 'active',
    renewals: 1,
  },
  {
    id: 'loan-0003',
    bookId: 'book-018',
    memberId: 'member-reader-3',
    issuedAt: daysAgo(3),
    dueDate: daysFromNow(11),
    returnedAt: null,
    status: 'active',
    renewals: 0,
  },
]);

export const RESERVATIONS: readonly Reservation[] = Object.freeze([
  {
    id: 'res-0001',
    bookId: 'book-007',
    memberId: 'member-reader-1',
    placedAt: daysAgo(4),
    active: true,
  },
  {
    id: 'res-0002',
    bookId: 'book-002',
    memberId: 'member-reader-4',
    placedAt: daysAgo(1),
    active: true,
  },
]);
