import type { EuLabelGrade, SpeedIndex, Tire, TireSeason } from '../models/tire.js';

// Local season aliases used by the seed entries. Define here so the literal
// string `'all-season'` doesn't appear N+ times in the file (avoids the
// `sonarjs/no-duplicate-string` lint guard).
const SUMMER: TireSeason = 'summer';
const WINTER: TireSeason = 'winter';
const ALL_SEASON: TireSeason = 'all-season';

/** Compact builder so the dataset stays readable. */
interface SeedEntry {
  readonly brand: string;
  readonly model: string;
  readonly width: number;
  readonly profile: number;
  readonly diameter: number;
  readonly season: TireSeason;
  readonly speedIndex: SpeedIndex;
  readonly loadIndex: number;
  readonly fuel: EuLabelGrade;
  readonly wet: EuLabelGrade;
  readonly noiseDb: number;
  readonly priceCents: number;
  readonly oldPriceCents?: number;
  readonly stock: number;
  readonly rating: number;
  readonly reviewCount: number;
  readonly description: string;
}

const SEED_ENTRIES: readonly SeedEntry[] = [
  // ─── Continental ─────────────────────────────────────────────
  {
    brand: 'Continental',
    model: 'PremiumContact 7',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 91,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 53900,
    oldPriceCents: 59900,
    stock: 24,
    rating: 4.7,
    reviewCount: 312,
    description: 'Topowa opona letnia premium, krótka droga hamowania na mokrym.',
  },
  {
    brand: 'Continental',
    model: 'PremiumContact 7',
    width: 225,
    profile: 45,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'W',
    loadIndex: 94,
    fuel: 'B',
    wet: 'A',
    noiseDb: 71,
    priceCents: 68500,
    stock: 16,
    rating: 4.7,
    reviewCount: 198,
    description: 'Wersja 17" — sportowa charakterystyka i komfort dalekobieżny.',
  },
  {
    brand: 'Continental',
    model: 'WinterContact TS 870',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 71,
    priceCents: 49900,
    stock: 30,
    rating: 4.6,
    reviewCount: 241,
    description: 'Sztandarowa opona zimowa, najwyższa nota na suchym i mokrym.',
  },
  {
    brand: 'Continental',
    model: 'AllSeasonContact 2',
    width: 215,
    profile: 60,
    diameter: 16,
    season: ALL_SEASON,
    speedIndex: 'H',
    loadIndex: 95,
    fuel: 'B',
    wet: 'B',
    noiseDb: 71,
    priceCents: 56700,
    stock: 18,
    rating: 4.5,
    reviewCount: 134,
    description: 'Całoroczna do regionów o łagodnej zimie.',
  },

  // ─── Michelin ────────────────────────────────────────────────
  {
    brand: 'Michelin',
    model: 'Primacy 4+',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 91,
    fuel: 'B',
    wet: 'A',
    noiseDb: 69,
    priceCents: 51900,
    stock: 22,
    rating: 4.6,
    reviewCount: 287,
    description: 'Niezawodna trwałość, niski opór toczenia.',
  },
  {
    brand: 'Michelin',
    model: 'Pilot Sport 4',
    width: 225,
    profile: 45,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'Y',
    loadIndex: 94,
    fuel: 'C',
    wet: 'A',
    noiseDb: 71,
    priceCents: 71500,
    oldPriceCents: 79900,
    stock: 9,
    rating: 4.8,
    reviewCount: 421,
    description: 'Sportowa opona dla wymagających kierowców.',
  },
  {
    brand: 'Michelin',
    model: 'Alpin 6',
    width: 195,
    profile: 65,
    diameter: 15,
    season: WINTER,
    speedIndex: 'T',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 69,
    priceCents: 39900,
    stock: 35,
    rating: 4.5,
    reviewCount: 156,
    description: 'Niezawodna zimowa do miasta i podmiejskich tras.',
  },
  {
    brand: 'Michelin',
    model: 'CrossClimate 2',
    width: 205,
    profile: 55,
    diameter: 16,
    season: ALL_SEASON,
    speedIndex: 'V',
    loadIndex: 94,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 58500,
    stock: 28,
    rating: 4.7,
    reviewCount: 389,
    description: 'Bezkonkurencyjna w segmencie całorocznym.',
  },
  {
    brand: 'Michelin',
    model: 'CrossClimate 2',
    width: 225,
    profile: 50,
    diameter: 17,
    season: ALL_SEASON,
    speedIndex: 'W',
    loadIndex: 98,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 67200,
    stock: 12,
    rating: 4.7,
    reviewCount: 201,
    description: 'Większy rozmiar dla SUV-ów i kompaktów premium.',
  },

  // ─── Bridgestone ─────────────────────────────────────────────
  {
    brand: 'Bridgestone',
    model: 'Turanza 6',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 91,
    fuel: 'A',
    wet: 'A',
    noiseDb: 69,
    priceCents: 52500,
    stock: 20,
    rating: 4.6,
    reviewCount: 178,
    description: 'Komfortowa premium z najlepszą klasą paliwową A.',
  },
  {
    brand: 'Bridgestone',
    model: 'Potenza Sport',
    width: 245,
    profile: 40,
    diameter: 18,
    season: SUMMER,
    speedIndex: 'Y',
    loadIndex: 97,
    fuel: 'C',
    wet: 'A',
    noiseDb: 73,
    priceCents: 89900,
    stock: 7,
    rating: 4.7,
    reviewCount: 96,
    description: 'Sportowa opona UHP do mocnych aut.',
  },
  {
    brand: 'Bridgestone',
    model: 'Blizzak LM005',
    width: 215,
    profile: 60,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 99,
    fuel: 'C',
    wet: 'B',
    noiseDb: 72,
    priceCents: 51200,
    stock: 19,
    rating: 4.5,
    reviewCount: 142,
    description: 'Wysoko ceniona opona zimowa.',
  },

  // ─── Goodyear ────────────────────────────────────────────────
  {
    brand: 'Goodyear',
    model: 'EfficientGrip Performance 2',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 94,
    fuel: 'A',
    wet: 'A',
    noiseDb: 67,
    priceCents: 50900,
    oldPriceCents: 55900,
    stock: 26,
    rating: 4.6,
    reviewCount: 220,
    description: 'Niski opór toczenia, świetne właściwości na mokrym.',
  },
  {
    brand: 'Goodyear',
    model: 'UltraGrip Performance 3',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 70,
    priceCents: 47500,
    stock: 22,
    rating: 4.5,
    reviewCount: 188,
    description: 'Sprawdzona zimowa w segmencie premium.',
  },
  {
    brand: 'Goodyear',
    model: 'Vector 4Seasons Gen-3',
    width: 195,
    profile: 65,
    diameter: 15,
    season: ALL_SEASON,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'B',
    wet: 'B',
    noiseDb: 69,
    priceCents: 43500,
    stock: 31,
    rating: 4.4,
    reviewCount: 263,
    description: 'Topowa całoroczna dla małych i kompaktowych aut.',
  },

  // ─── Pirelli ─────────────────────────────────────────────────
  {
    brand: 'Pirelli',
    model: 'Cinturato P7',
    width: 225,
    profile: 45,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'W',
    loadIndex: 94,
    fuel: 'B',
    wet: 'A',
    noiseDb: 71,
    priceCents: 65900,
    stock: 14,
    rating: 4.5,
    reviewCount: 167,
    description: 'Premium summer dla sedanów średniej klasy.',
  },
  {
    brand: 'Pirelli',
    model: 'P Zero',
    width: 245,
    profile: 35,
    diameter: 19,
    season: SUMMER,
    speedIndex: 'Y',
    loadIndex: 93,
    fuel: 'C',
    wet: 'A',
    noiseDb: 73,
    priceCents: 109900,
    stock: 5,
    rating: 4.8,
    reviewCount: 78,
    description: 'Topowa opona dla aut sportowych i premium SUV.',
  },
  {
    brand: 'Pirelli',
    model: 'Winter Sottozero 3',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 70,
    priceCents: 49800,
    stock: 17,
    rating: 4.5,
    reviewCount: 134,
    description: 'Zimowa opona z włoskim DNA.',
  },
  {
    brand: 'Pirelli',
    model: 'Cinturato All Season SF2',
    width: 215,
    profile: 55,
    diameter: 17,
    season: ALL_SEASON,
    speedIndex: 'V',
    loadIndex: 98,
    fuel: 'B',
    wet: 'A',
    noiseDb: 71,
    priceCents: 59500,
    stock: 13,
    rating: 4.6,
    reviewCount: 95,
    description: 'Komfortowa całoroczna dla wymagających.',
  },

  // ─── Dunlop ──────────────────────────────────────────────────
  {
    brand: 'Dunlop',
    model: 'Sport BluResponse',
    width: 195,
    profile: 65,
    diameter: 15,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 91,
    fuel: 'A',
    wet: 'A',
    noiseDb: 68,
    priceCents: 38900,
    stock: 41,
    rating: 4.4,
    reviewCount: 312,
    description: 'Świetna relacja cena/jakość w klasie kompaktowej.',
  },
  {
    brand: 'Dunlop',
    model: 'Winter Sport 5',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 71,
    priceCents: 41500,
    stock: 27,
    rating: 4.4,
    reviewCount: 186,
    description: 'Pewna zimowa do różnych warunków.',
  },

  // ─── Hankook ─────────────────────────────────────────────────
  {
    brand: 'Hankook',
    model: 'Ventus Prime 4',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 94,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 39900,
    stock: 33,
    rating: 4.5,
    reviewCount: 245,
    description: 'Atrakcyjna cenowo opona klasy średniej premium.',
  },
  {
    brand: 'Hankook',
    model: 'Winter i*cept RS3',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'C',
    noiseDb: 72,
    priceCents: 32900,
    stock: 38,
    rating: 4.3,
    reviewCount: 159,
    description: 'Tańsza zimowa z dobrymi opiniami.',
  },
  {
    brand: 'Hankook',
    model: 'Kinergy 4S2',
    width: 215,
    profile: 60,
    diameter: 16,
    season: ALL_SEASON,
    speedIndex: 'H',
    loadIndex: 95,
    fuel: 'B',
    wet: 'B',
    noiseDb: 71,
    priceCents: 37500,
    stock: 25,
    rating: 4.4,
    reviewCount: 198,
    description: 'Solidna całoroczna w przystępnej cenie.',
  },

  // ─── Nokian ──────────────────────────────────────────────────
  {
    brand: 'Nokian',
    model: 'Wetproof 1',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 91,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 43900,
    stock: 21,
    rating: 4.5,
    reviewCount: 134,
    description: 'Stworzona z myślą o europejskich opadach.',
  },
  {
    brand: 'Nokian',
    model: 'Snowproof 1',
    width: 195,
    profile: 65,
    diameter: 15,
    season: WINTER,
    speedIndex: 'T',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 69,
    priceCents: 36900,
    stock: 29,
    rating: 4.6,
    reviewCount: 167,
    description: 'Skandynawska zimówka — pewna na śniegu i lodzie.',
  },
  {
    brand: 'Nokian',
    model: 'Seasonproof 1',
    width: 205,
    profile: 55,
    diameter: 16,
    season: ALL_SEASON,
    speedIndex: 'V',
    loadIndex: 94,
    fuel: 'B',
    wet: 'B',
    noiseDb: 71,
    priceCents: 41500,
    stock: 23,
    rating: 4.4,
    reviewCount: 112,
    description: 'Całoroczna z myślą o północnych warunkach.',
  },

  // ─── Kumho ───────────────────────────────────────────────────
  {
    brand: 'Kumho',
    model: 'Ecsta HS52',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 94,
    fuel: 'B',
    wet: 'B',
    noiseDb: 70,
    priceCents: 33900,
    oldPriceCents: 37900,
    stock: 44,
    rating: 4.3,
    reviewCount: 211,
    description: 'Budżetowa opona letnia z dobrym przyczepieniem.',
  },
  {
    brand: 'Kumho',
    model: 'WinterCraft WP72',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 94,
    fuel: 'C',
    wet: 'C',
    noiseDb: 72,
    priceCents: 28900,
    stock: 52,
    rating: 4.2,
    reviewCount: 178,
    description: 'Tania zimówka klasy ekonomicznej.',
  },

  // ─── Yokohama ────────────────────────────────────────────────
  {
    brand: 'Yokohama',
    model: 'BluEarth-GT AE51',
    width: 215,
    profile: 55,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'W',
    loadIndex: 94,
    fuel: 'A',
    wet: 'A',
    noiseDb: 70,
    priceCents: 49900,
    stock: 18,
    rating: 4.5,
    reviewCount: 143,
    description: 'Najwyższe noty paliwowe w niższej cenie premium.',
  },
  {
    brand: 'Yokohama',
    model: 'BluEarth-Winter V906',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 71,
    priceCents: 36900,
    stock: 24,
    rating: 4.4,
    reviewCount: 102,
    description: 'Komfortowa zimowa z japońskim know-how.',
  },

  // ─── Falken ──────────────────────────────────────────────────
  {
    brand: 'Falken',
    model: 'Azenis FK520',
    width: 225,
    profile: 45,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'Y',
    loadIndex: 94,
    fuel: 'B',
    wet: 'A',
    noiseDb: 71,
    priceCents: 42900,
    stock: 27,
    rating: 4.4,
    reviewCount: 156,
    description: 'UHP opona letnia w atrakcyjnej cenie.',
  },
  {
    brand: 'Falken',
    model: 'Eurowinter HS01',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 71,
    priceCents: 31500,
    stock: 39,
    rating: 4.3,
    reviewCount: 195,
    description: 'Niedroga zimówka klasy średniej.',
  },

  // ─── Uniroyal ────────────────────────────────────────────────
  {
    brand: 'Uniroyal',
    model: 'RainSport 5',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 91,
    fuel: 'B',
    wet: 'A',
    noiseDb: 71,
    priceCents: 36500,
    stock: 31,
    rating: 4.5,
    reviewCount: 287,
    description: 'Specjalista od jazdy na mokrym.',
  },
  {
    brand: 'Uniroyal',
    model: 'WinterExpert',
    width: 195,
    profile: 65,
    diameter: 15,
    season: WINTER,
    speedIndex: 'T',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 71,
    priceCents: 27900,
    stock: 47,
    rating: 4.3,
    reviewCount: 154,
    description: 'Klasyczna zimówka segmentu ekonomicznego.',
  },
  {
    brand: 'Uniroyal',
    model: 'AllSeasonExpert 2',
    width: 205,
    profile: 55,
    diameter: 16,
    season: ALL_SEASON,
    speedIndex: 'H',
    loadIndex: 94,
    fuel: 'B',
    wet: 'B',
    noiseDb: 71,
    priceCents: 33500,
    stock: 36,
    rating: 4.4,
    reviewCount: 169,
    description: 'Atrakcyjna cenowo całoroczna.',
  },

  // ─── Vredestein ──────────────────────────────────────────────
  {
    brand: 'Vredestein',
    model: 'Ultrac',
    width: 225,
    profile: 45,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'W',
    loadIndex: 94,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 52900,
    stock: 12,
    rating: 4.6,
    reviewCount: 89,
    description: 'Holenderska premium z włoskim designem.',
  },
  {
    brand: 'Vredestein',
    model: 'Wintrac Pro',
    width: 225,
    profile: 50,
    diameter: 17,
    season: WINTER,
    speedIndex: 'V',
    loadIndex: 98,
    fuel: 'C',
    wet: 'B',
    noiseDb: 71,
    priceCents: 48900,
    stock: 14,
    rating: 4.5,
    reviewCount: 76,
    description: 'Premium zimówka SUV-owa.',
  },
  {
    brand: 'Vredestein',
    model: 'Quatrac',
    width: 205,
    profile: 55,
    diameter: 16,
    season: ALL_SEASON,
    speedIndex: 'V',
    loadIndex: 94,
    fuel: 'B',
    wet: 'B',
    noiseDb: 70,
    priceCents: 44500,
    stock: 19,
    rating: 4.5,
    reviewCount: 132,
    description: 'Sprawdzona całoroczna 5-gwiazdkowa.',
  },

  // ─── Cooper ──────────────────────────────────────────────────
  {
    brand: 'Cooper',
    model: 'Zeon CS8',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 91,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 31900,
    stock: 28,
    rating: 4.3,
    reviewCount: 87,
    description: 'Konkurencyjna cenowo opona letnia.',
  },
  {
    brand: 'Cooper',
    model: 'Discoverer Winter',
    width: 215,
    profile: 60,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 99,
    fuel: 'C',
    wet: 'B',
    noiseDb: 72,
    priceCents: 35900,
    stock: 21,
    rating: 4.2,
    reviewCount: 64,
    description: 'SUV-owa zimówka klasy ekonomicznej.',
  },

  // ─── Toyo ────────────────────────────────────────────────────
  {
    brand: 'Toyo',
    model: 'Proxes Comfort',
    width: 215,
    profile: 55,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'W',
    loadIndex: 94,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 41500,
    stock: 23,
    rating: 4.4,
    reviewCount: 121,
    description: 'Komfortowa premium z Japonii.',
  },
  {
    brand: 'Toyo',
    model: 'Snowprox S944',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'C',
    noiseDb: 72,
    priceCents: 32500,
    stock: 34,
    rating: 4.2,
    reviewCount: 108,
    description: 'Solidna zimówka z japońską inżynierią.',
  },
  {
    brand: 'Toyo',
    model: 'Celsius',
    width: 205,
    profile: 55,
    diameter: 16,
    season: ALL_SEASON,
    speedIndex: 'V',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 71,
    priceCents: 35900,
    stock: 22,
    rating: 4.3,
    reviewCount: 96,
    description: 'Całoroczna z japońską jakością.',
  },

  // ─── Maxxis ──────────────────────────────────────────────────
  {
    brand: 'Maxxis',
    model: 'Premitra 5',
    width: 205,
    profile: 55,
    diameter: 16,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 94,
    fuel: 'B',
    wet: 'A',
    noiseDb: 70,
    priceCents: 28500,
    stock: 45,
    rating: 4.2,
    reviewCount: 234,
    description: 'Świetna opcja budżetowa.',
  },
  {
    brand: 'Maxxis',
    model: 'Premitra Ice Nord WP6',
    width: 195,
    profile: 65,
    diameter: 15,
    season: WINTER,
    speedIndex: 'T',
    loadIndex: 95,
    fuel: 'C',
    wet: 'B',
    noiseDb: 70,
    priceCents: 24900,
    stock: 51,
    rating: 4.1,
    reviewCount: 178,
    description: 'Najtańsza zimówka w katalogu z niezłymi ocenami.',
  },
  {
    brand: 'Maxxis',
    model: 'Premitra All Season AP3',
    width: 195,
    profile: 65,
    diameter: 15,
    season: ALL_SEASON,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 71,
    priceCents: 26900,
    stock: 33,
    rating: 4.2,
    reviewCount: 142,
    description: 'Tania całoroczna do małych aut.',
  },

  // ─── Sava ────────────────────────────────────────────────────
  {
    brand: 'Sava',
    model: 'Intensa UHP 2',
    width: 225,
    profile: 45,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'Y',
    loadIndex: 94,
    fuel: 'B',
    wet: 'B',
    noiseDb: 71,
    priceCents: 32900,
    stock: 26,
    rating: 4.3,
    reviewCount: 156,
    description: 'UHP opona w bardzo dobrej cenie.',
  },
  {
    brand: 'Sava',
    model: 'Eskimo HP2',
    width: 205,
    profile: 55,
    diameter: 16,
    season: WINTER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'C',
    noiseDb: 72,
    priceCents: 25900,
    stock: 41,
    rating: 4.1,
    reviewCount: 132,
    description: 'Najtańsza zimówka klasy premium-budżet.',
  },

  // ─── Debica ──────────────────────────────────────────────────
  {
    brand: 'Debica',
    model: 'Presto',
    width: 195,
    profile: 65,
    diameter: 15,
    season: SUMMER,
    speedIndex: 'H',
    loadIndex: 91,
    fuel: 'C',
    wet: 'B',
    noiseDb: 70,
    priceCents: 22900,
    stock: 67,
    rating: 4.0,
    reviewCount: 287,
    description: 'Polska marka, ekonomiczny wybór.',
  },
  {
    brand: 'Debica',
    model: 'Frigo 2',
    width: 195,
    profile: 65,
    diameter: 15,
    season: WINTER,
    speedIndex: 'T',
    loadIndex: 91,
    fuel: 'E',
    wet: 'C',
    noiseDb: 71,
    priceCents: 19900,
    stock: 89,
    rating: 3.9,
    reviewCount: 234,
    description: 'Bardzo budżetowa zimówka.',
  },

  // ─── Larger sizes / specials ─────────────────────────────────
  {
    brand: 'Continental',
    model: 'CrossContact ATR',
    width: 235,
    profile: 70,
    diameter: 16,
    season: ALL_SEASON,
    speedIndex: 'H',
    loadIndex: 106,
    fuel: 'C',
    wet: 'B',
    noiseDb: 73,
    priceCents: 76900,
    stock: 8,
    rating: 4.6,
    reviewCount: 67,
    description: 'Terenowa premium do lekkiego offroadu.',
  },
  {
    brand: 'Michelin',
    model: 'Latitude Sport 3',
    width: 235,
    profile: 55,
    diameter: 18,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 100,
    fuel: 'C',
    wet: 'A',
    noiseDb: 72,
    priceCents: 89500,
    oldPriceCents: 95900,
    stock: 6,
    rating: 4.7,
    reviewCount: 89,
    description: 'Sportowa premium SUV-owa.',
  },
  {
    brand: 'Bridgestone',
    model: 'Dueler H/P Sport',
    width: 255,
    profile: 55,
    diameter: 18,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 109,
    fuel: 'C',
    wet: 'B',
    noiseDb: 73,
    priceCents: 92500,
    stock: 4,
    rating: 4.5,
    reviewCount: 56,
    description: 'Duże SUV-y i terenówki.',
  },
  {
    brand: 'Goodyear',
    model: 'Wrangler All-Terrain Adventure',
    width: 245,
    profile: 65,
    diameter: 17,
    season: ALL_SEASON,
    speedIndex: 'T',
    loadIndex: 111,
    fuel: 'C',
    wet: 'C',
    noiseDb: 73,
    priceCents: 78900,
    stock: 11,
    rating: 4.5,
    reviewCount: 78,
    description: 'Klasyk All-Terrain do crossoverów.',
  },
  {
    brand: 'Pirelli',
    model: 'Scorpion Verde',
    width: 235,
    profile: 60,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 102,
    fuel: 'B',
    wet: 'A',
    noiseDb: 71,
    priceCents: 71900,
    stock: 13,
    rating: 4.6,
    reviewCount: 102,
    description: 'Premium SUV o niskim oporze toczenia.',
  },
  {
    brand: 'Hankook',
    model: 'Dynapro HP2',
    width: 235,
    profile: 60,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'V',
    loadIndex: 102,
    fuel: 'B',
    wet: 'B',
    noiseDb: 71,
    priceCents: 49900,
    stock: 22,
    rating: 4.4,
    reviewCount: 145,
    description: 'Dobra alternatywa do SUV w średnim segmencie.',
  },
  {
    brand: 'Yokohama',
    model: 'Geolandar SUV',
    width: 215,
    profile: 60,
    diameter: 17,
    season: SUMMER,
    speedIndex: 'H',
    loadIndex: 96,
    fuel: 'B',
    wet: 'B',
    noiseDb: 70,
    priceCents: 41900,
    stock: 17,
    rating: 4.3,
    reviewCount: 78,
    description: 'SUV-owa opona Yokohamy.',
  },
];

/**
 * Build a `Tire[]` snapshot with deterministic ids and CDN placeholder image
 * URLs. `picsum.photos/seed/{id}` returns a stable image per seed so reloads
 * never reshuffle the gallery.
 */
function buildCatalogue(): readonly Tire[] {
  return SEED_ENTRIES.map((entry, index) => {
    const id = `tire-${String(index + 1).padStart(3, '0')}`;
    return {
      id,
      brand: entry.brand,
      model: entry.model,
      size: { width: entry.width, profile: entry.profile, diameter: entry.diameter },
      season: entry.season,
      speedIndex: entry.speedIndex,
      loadIndex: entry.loadIndex,
      euLabel: { fuel: entry.fuel, wet: entry.wet, noiseDb: entry.noiseDb },
      priceCents: entry.priceCents,
      oldPriceCents: entry.oldPriceCents ?? null,
      stock: entry.stock,
      rating: entry.rating,
      reviewCount: entry.reviewCount,
      imageUrl: `https://picsum.photos/seed/${id}/600/600`,
      description: entry.description,
    } satisfies Tire;
  });
}

/** Frozen catalogue snapshot — re-built lazily on first import. */
export const TIRE_CATALOGUE: readonly Tire[] = Object.freeze(buildCatalogue());
