export const LOAN_TYPE_OPTIONS = [
  { value: 'mortgage', label: 'Hipoteczny' },
  { value: 'cash', label: 'Gotówkowy' },
  { value: 'business', label: 'Firmowy' },
] as const;

export type LoanType = (typeof LOAN_TYPE_OPTIONS)[number]['value'];

export const RATE_MODE_OPTIONS = [
  { value: 'fixed', label: 'Stałe oprocentowanie' },
  { value: 'variable', label: 'Zmienne oprocentowanie' },
  { value: 'mixed', label: 'Okresowo stałe' },
] as const;

export type RateMode = (typeof RATE_MODE_OPTIONS)[number]['value'];

export interface CreditOffer {
  id: string;
  bankName: string;
  productName: string;
  countryCode: string;
  loanType: LoanType;
  rateMode: RateMode;
  currencyCode: string;
  minAmount: number;
  maxAmount: number;
  minTermMonths: number;
  maxTermMonths: number;
  apr: number;
  nominalRate: number;
  monthlyInstallment: number;
  totalCost: number;
  decisionDays: number;
  maxLtv?: number;
  badge?: string;
  highlights: readonly string[];
}

export const CREDIT_OFFERS: readonly CreditOffer[] = [
  {
    id: 'pl-santander-housing-stable',
    bankName: 'Santander Bank Polska',
    productName: 'Hipoteka Stabilna Start',
    countryCode: 'PL',
    loanType: 'mortgage',
    rateMode: 'mixed',
    currencyCode: 'EUR',
    minAmount: 120000,
    maxAmount: 800000,
    minTermMonths: 120,
    maxTermMonths: 360,
    apr: 4.82,
    nominalRate: 4.41,
    monthlyInstallment: 1538,
    totalCost: 135200,
    decisionDays: 5,
    maxLtv: 80,
    badge: 'Najczęściej wybierana',
    highlights: ['Decyzja w 5 dni', 'Nadpłata bez prowizji po 36 mies.', 'Obsługa online'],
  },
  {
    id: 'pl-mbank-green-mortgage',
    bankName: 'mBank',
    productName: 'eHipoteka Green',
    countryCode: 'PL',
    loanType: 'mortgage',
    rateMode: 'fixed',
    currencyCode: 'EUR',
    minAmount: 150000,
    maxAmount: 900000,
    minTermMonths: 120,
    maxTermMonths: 360,
    apr: 4.51,
    nominalRate: 4.08,
    monthlyInstallment: 1494,
    totalCost: 126900,
    decisionDays: 4,
    maxLtv: 85,
    badge: 'Green home',
    highlights: ['Stała rata przez 5 lat', 'Rabat za klasę energetyczną A/B', 'Wycena online'],
  },
  {
    id: 'pl-ing-cash-online',
    bankName: 'ING Bank Śląski',
    productName: 'Pożyczka online Direct',
    countryCode: 'PL',
    loanType: 'cash',
    rateMode: 'fixed',
    currencyCode: 'EUR',
    minAmount: 5000,
    maxAmount: 60000,
    minTermMonths: 12,
    maxTermMonths: 96,
    apr: 8.9,
    nominalRate: 8.12,
    monthlyInstallment: 612,
    totalCost: 13980,
    decisionDays: 1,
    badge: '100% digital',
    highlights: ['Wypłata tego samego dnia', 'Brak wizyty w oddziale', 'Ubezpieczenie opcjonalne'],
  },
  {
    id: 'de-db-baufinanz-fix',
    bankName: 'Deutsche Bank',
    productName: 'BauFinanz 10Y Fix',
    countryCode: 'DE',
    loanType: 'mortgage',
    rateMode: 'fixed',
    currencyCode: 'EUR',
    minAmount: 180000,
    maxAmount: 1250000,
    minTermMonths: 120,
    maxTermMonths: 360,
    apr: 4.12,
    nominalRate: 3.84,
    monthlyInstallment: 1422,
    totalCost: 118100,
    decisionDays: 6,
    maxLtv: 82,
    badge: 'Najniższe RRSO',
    highlights: ['Stałe oprocentowanie 10 lat', 'Refinansowanie w pakiecie', 'Dedykowany opiekun'],
  },
  {
    id: 'de-commerzbank-flex-credit',
    bankName: 'Commerzbank',
    productName: 'FlexCredit Privat',
    countryCode: 'DE',
    loanType: 'cash',
    rateMode: 'variable',
    currencyCode: 'EUR',
    minAmount: 10000,
    maxAmount: 90000,
    minTermMonths: 12,
    maxTermMonths: 84,
    apr: 7.25,
    nominalRate: 6.91,
    monthlyInstallment: 488,
    totalCost: 10960,
    decisionDays: 2,
    highlights: ['Karencja 2 miesiące', 'Wcześniejsza spłata z niską opłatą', 'Weryfikacja PSD2'],
  },
  {
    id: 'fr-bnp-habitat-flex',
    bankName: 'BNP Paribas',
    productName: 'Prêt Habitat Flex',
    countryCode: 'FR',
    loanType: 'mortgage',
    rateMode: 'mixed',
    currencyCode: 'EUR',
    minAmount: 160000,
    maxAmount: 950000,
    minTermMonths: 120,
    maxTermMonths: 300,
    apr: 4.36,
    nominalRate: 4.01,
    monthlyInstallment: 1468,
    totalCost: 123450,
    decisionDays: 7,
    maxLtv: 80,
    highlights: ['Stała stopa 7 lat', 'Oferta dla rezydentów UE', 'Monitorowanie budżetu domowego'],
  },
  {
    id: 'es-caixabank-mortgage',
    bankName: 'CaixaBank',
    productName: 'Hipoteca Casa Flexible',
    countryCode: 'ES',
    loanType: 'mortgage',
    rateMode: 'variable',
    currencyCode: 'EUR',
    minAmount: 140000,
    maxAmount: 850000,
    minTermMonths: 120,
    maxTermMonths: 360,
    apr: 4.74,
    nominalRate: 4.22,
    monthlyInstallment: 1518,
    totalCost: 131100,
    decisionDays: 8,
    maxLtv: 75,
    highlights: ['Powiązanie z kontem premium', 'Aktualizacja oferty co kwartał', 'Obsługa dokumentów online'],
  },
  {
    id: 'es-bbva-business-growth',
    bankName: 'BBVA',
    productName: 'Business Growth Loan',
    countryCode: 'ES',
    loanType: 'business',
    rateMode: 'mixed',
    currencyCode: 'EUR',
    minAmount: 50000,
    maxAmount: 450000,
    minTermMonths: 24,
    maxTermMonths: 180,
    apr: 6.18,
    nominalRate: 5.87,
    monthlyInstallment: 1884,
    totalCost: 56800,
    decisionDays: 3,
    highlights: ['Zabezpieczenie częściowo gwarancyjne', 'Szybka analiza cash flow', 'Możliwość wakacji kredytowych'],
  },
  {
    id: 'it-unicredit-mutuo-green',
    bankName: 'UniCredit',
    productName: 'Mutuo Casa Green',
    countryCode: 'IT',
    loanType: 'mortgage',
    rateMode: 'fixed',
    currencyCode: 'EUR',
    minAmount: 150000,
    maxAmount: 980000,
    minTermMonths: 120,
    maxTermMonths: 360,
    apr: 4.29,
    nominalRate: 3.96,
    monthlyInstallment: 1451,
    totalCost: 121600,
    decisionDays: 6,
    maxLtv: 80,
    highlights: [
      'Niższa marża dla nieruchomości klasy A',
      'Symulacja zdolności w aplikacji',
      'Akceptacja podpisu kwalifikowanego',
    ],
  },
  {
    id: 'nl-ing-woning-hypotheek',
    bankName: 'ING Netherlands',
    productName: 'Woning Hypotheek Plus',
    countryCode: 'NL',
    loanType: 'mortgage',
    rateMode: 'fixed',
    currencyCode: 'EUR',
    minAmount: 220000,
    maxAmount: 1200000,
    minTermMonths: 120,
    maxTermMonths: 360,
    apr: 4.23,
    nominalRate: 3.93,
    monthlyInstallment: 1440,
    totalCost: 120220,
    decisionDays: 5,
    maxLtv: 90,
    highlights: ['LTV do 90%', 'Dashboard kosztów stałych', 'Szybki refinancing'],
  },
  {
    id: 'ie-boi-green-mortgage',
    bankName: 'Bank of Ireland',
    productName: 'Green Mortgage 4Y',
    countryCode: 'IE',
    loanType: 'mortgage',
    rateMode: 'fixed',
    currencyCode: 'EUR',
    minAmount: 180000,
    maxAmount: 920000,
    minTermMonths: 120,
    maxTermMonths: 420,
    apr: 4.41,
    nominalRate: 4.05,
    monthlyInstallment: 1476,
    totalCost: 124110,
    decisionDays: 4,
    maxLtv: 80,
    highlights: ['Stała stopa 4 lata', 'Oferta dla zakupu pierwszego domu', 'Rabat za zieloną nieruchomość'],
  },
  {
    id: 'cz-ceska-hypoteka',
    bankName: 'Česká spořitelna',
    productName: 'Hypotéka Premium',
    countryCode: 'CZ',
    loanType: 'mortgage',
    rateMode: 'fixed',
    currencyCode: 'EUR',
    minAmount: 100000,
    maxAmount: 650000,
    minTermMonths: 120,
    maxTermMonths: 360,
    apr: 4.68,
    nominalRate: 4.19,
    monthlyInstallment: 1503,
    totalCost: 128540,
    decisionDays: 6,
    maxLtv: 80,
    highlights: ['Decyzja w 48h dla klientów premium', 'Dodatkowy limit remontowy', 'Możliwość łączenia dochodów'],
  },
] as const;
